/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideocastRouteImport } from './routes/videocast'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as GameRouteImport } from './routes/game'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChildrensBookRouteImport } from './routes/childrens-book'
import { Route as IndexRouteImport } from './routes/index'

const VideocastRoute = VideocastRouteImport.update({
  id: '/videocast',
  path: '/videocast',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrensBookRoute = ChildrensBookRouteImport.update({
  id: '/childrens-book',
  path: '/childrens-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/childrens-book': typeof ChildrensBookRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/our-story': typeof OurStoryRoute
  '/our-team': typeof OurTeamRoute
  '/videocast': typeof VideocastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/childrens-book': typeof ChildrensBookRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/our-story': typeof OurStoryRoute
  '/our-team': typeof OurTeamRoute
  '/videocast': typeof VideocastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/childrens-book': typeof ChildrensBookRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/our-story': typeof OurStoryRoute
  '/our-team': typeof OurTeamRoute
  '/videocast': typeof VideocastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/childrens-book'
    | '/contact'
    | '/game'
    | '/our-story'
    | '/our-team'
    | '/videocast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/childrens-book'
    | '/contact'
    | '/game'
    | '/our-story'
    | '/our-team'
    | '/videocast'
  id:
    | '__root__'
    | '/'
    | '/childrens-book'
    | '/contact'
    | '/game'
    | '/our-story'
    | '/our-team'
    | '/videocast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildrensBookRoute: typeof ChildrensBookRoute
  ContactRoute: typeof ContactRoute
  GameRoute: typeof GameRoute
  OurStoryRoute: typeof OurStoryRoute
  OurTeamRoute: typeof OurTeamRoute
  VideocastRoute: typeof VideocastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videocast': {
      id: '/videocast'
      path: '/videocast'
      fullPath: '/videocast'
      preLoaderRoute: typeof VideocastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/childrens-book': {
      id: '/childrens-book'
      path: '/childrens-book'
      fullPath: '/childrens-book'
      preLoaderRoute: typeof ChildrensBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildrensBookRoute: ChildrensBookRoute,
  ContactRoute: ContactRoute,
  GameRoute: GameRoute,
  OurStoryRoute: OurStoryRoute,
  OurTeamRoute: OurTeamRoute,
  VideocastRoute: VideocastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
